/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedUebersichtRouteImport } from './routes/_authenticated/uebersicht'
import { Route as AuthenticatedBaustellenIndexRouteImport } from './routes/_authenticated/baustellen/index'
import { Route as AuthenticatedBaustellenNeuRouteImport } from './routes/_authenticated/baustellen/neu'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUebersichtRoute = AuthenticatedUebersichtRouteImport.update({
  id: '/uebersicht',
  path: '/uebersicht',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBaustellenIndexRoute =
  AuthenticatedBaustellenIndexRouteImport.update({
    id: '/baustellen/',
    path: '/baustellen/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBaustellenNeuRoute =
  AuthenticatedBaustellenNeuRouteImport.update({
    id: '/baustellen/neu',
    path: '/baustellen/neu',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/uebersicht': typeof AuthenticatedUebersichtRoute
  '/baustellen/neu': typeof AuthenticatedBaustellenNeuRoute
  '/baustellen/': typeof AuthenticatedBaustellenIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/uebersicht': typeof AuthenticatedUebersichtRoute
  '/baustellen/neu': typeof AuthenticatedBaustellenNeuRoute
  '/baustellen': typeof AuthenticatedBaustellenIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/uebersicht': typeof AuthenticatedUebersichtRoute
  '/_authenticated/baustellen/neu': typeof AuthenticatedBaustellenNeuRoute
  '/_authenticated/baustellen/': typeof AuthenticatedBaustellenIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/uebersicht' | '/baustellen/neu' | '/baustellen/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/uebersicht' | '/baustellen/neu' | '/baustellen'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/uebersicht'
    | '/_authenticated/baustellen/neu'
    | '/_authenticated/baustellen/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/uebersicht': {
      id: '/_authenticated/uebersicht'
      path: '/uebersicht'
      fullPath: '/uebersicht'
      preLoaderRoute: typeof AuthenticatedUebersichtRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/baustellen/': {
      id: '/_authenticated/baustellen/'
      path: '/baustellen'
      fullPath: '/baustellen/'
      preLoaderRoute: typeof AuthenticatedBaustellenIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/baustellen/neu': {
      id: '/_authenticated/baustellen/neu'
      path: '/baustellen/neu'
      fullPath: '/baustellen/neu'
      preLoaderRoute: typeof AuthenticatedBaustellenNeuRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedUebersichtRoute: typeof AuthenticatedUebersichtRoute
  AuthenticatedBaustellenNeuRoute: typeof AuthenticatedBaustellenNeuRoute
  AuthenticatedBaustellenIndexRoute: typeof AuthenticatedBaustellenIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedUebersichtRoute: AuthenticatedUebersichtRoute,
  AuthenticatedBaustellenNeuRoute: AuthenticatedBaustellenNeuRoute,
  AuthenticatedBaustellenIndexRoute: AuthenticatedBaustellenIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
